name: Exécuter mon code
on: [push, workflow_dispatch]  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  
    
    - name: Exécuter Python
      run: |
        python app.py     
      
    - name: Compiler C++
      run: gcc main.c -o main && ./main
    
    - name: Node.js
      run: node index.js

